---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family|lower }}.yml"

- name: Include general variables
  include_vars: ntp.yml

- name: Ensure NTP-related packages are installed
  package:
    name: ntp
    state: present

- name: Ensure tzdata package is installed (Linux)
  package:
    name: "{{ ntp_tzdata_package }}"
    state: present
  when: ansible_system == "Linux"

- name: Configure system timezone ({{ ntp_timezone }})
  timezone:
    name: "{{ ntp_timezone }}"

- name: Generate ntp.conf file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    mode: 0644
  notify: restart ntp

- name: Ensure NTP service is started on boot
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: yes
